### ISSUE TITLE
Attempting to access licensed features causes the Add-on to fail if all servers are at the 'None' license

### ISSUE THREAD

**Issue by jerewill-cisco** [jerewill-cisco/intersight-splunk-addon#8]
At least one server must have Essentials level license or higher or the call to cond/HclStatuses will fail.

Output from logs will be similar to this...

``` log
022-06-27 17:52:35,303 INFO pid=15412 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving compute HCL status...
2022-06-27 17:52:35,441 ERROR pid=15412 tid=MainThread file=base_modinput.py:log_error:309 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-intersight-addon/bin/ta_intersight_addon/aob_py3/modinput_wrapper/base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/TA-intersight-addon/bin/intersight.py", line 92, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/TA-intersight-addon/bin/input_module_intersight.py", line 381, in collect_events
    for data in RESPONSE.json()['Results']:
KeyError: 'Results'
```

**Comment by jerewill-cisco** [comment]
While first observed with the Compute inventory, this issue equally affects the Advisories inventory.  I've tested a fix for the next release.

**Comment by jerewill-cisco** [comment]
failed attempts to access licensed features will be logged...

``` log
2022-06-27 19:22:12,785 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Starting input named EXAMPLE
2022-06-27 19:22:12,786 INFO pid=22888 tid=MainThread file=setup_util.py:log_info:117 | Proxy is not enabled!
2022-06-27 19:22:12,929 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Connected to Intersight SaaS account named EXAMPLE
2022-06-27 19:22:12,929 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving Audit Records...
2022-06-27 19:22:12,929 INFO pid=22888 tid=MainThread file=splunk_rest_client.py:_request_handler:99 | Use HTTP connection pooling
2022-06-27 19:22:13,099 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving Alarms...
2022-06-27 19:22:13,200 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving Advisories...
2022-06-27 19:22:13,290 WARNING pid=22888 tid=MainThread file=base_modinput.py:log_warning:302 | EXAMPLE | Advisories error code is UnauthorizedOperation
2022-06-27 19:22:13,290 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving compute inventory...
2022-06-27 19:22:13,428 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving compute HCL status...
2022-06-27 19:22:13,519 WARNING pid=22888 tid=MainThread file=base_modinput.py:log_warning:302 | EXAMPLE | HCL error code is UnauthorizedOperation
2022-06-27 19:22:13,519 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving contract status items...
2022-06-27 19:22:13,672 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving network inventory...
2022-06-27 19:22:13,750 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving target inventory...
2022-06-27 19:22:13,897 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving Hyperflex cluster inventory...
2022-06-27 19:22:14,057 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | Retrieving Hyperflex node inventory...
2022-06-27 19:22:14,221 INFO pid=22888 tid=MainThread file=base_modinput.py:log_info:295 | EXAMPLE | FINISHED
```
